# docker-compose.yml
name: ${PROJECT_NAME}

services:
  db:
    image: postgres:16-alpine
    container_name: ${PROJECT_NAME}-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      TZ: Asia/Bangkok
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"                  
    restart: unless-stopped
    networks: [app-net]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: ${PROJECT_NAME}-redis
    command: ["redis-server", "--appendonly", "yes"]  
    ports:
      - "6379:6379"              
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks: [app-net]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile      
    container_name: ${PROJECT_NAME}-backend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      NODE_ENV: development
      TZ: Asia/Bangkok
      PORT: ${PORT}
      
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379/0
     
      STRIPE_PUBLIC_KEY: ${STRIPE_PUBLIC_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      STRIPE_CURRENCY: ${STRIPE_CURRENCY}
     
      # CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:${FRONT_END_PORT:-3000}}
    ports:
      - "${PORT}:8081"
    volumes:
      - ./:/app
      - /app/node_modules
    command: >
      sh -lc "
        npx prisma generate &&
        npx prisma migrate deploy &&
        npm run dev
      "
    restart: unless-stopped
    #เอาconไปอยู่ใน networkนี้
    networks: [app-net]
    healthcheck:
      test: ["CMD-SHELL", "node -e \"http=require('http');http.get('http://localhost:8081/health',r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))\""]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  # frontend:
    
  #   build:
  #     context: ./frontend        
  #     dockerfile: ./Dockerfile   
  #   container_name: ${PROJECT_NAME:-fintech}-frontend
  #   environment:
  #     TZ: Asia/Bangkok
      
  #     VITE_BACK_END_URL: http://${PROJECT_NAME:-fintech}-backend:8081
      
  #     FRONT_END_PORT: "${FRONT_END_PORT:-3000}"
  #   ports:
  #     - "${FRONT_END_PORT:-3000}:3000"
  #   volumes:
  #     - ./frontend:/app           
  #     - /app/node_modules
  #   command: >
  #     sh -lc "
  #       npm ci || npm i &&
  #       npm run dev -- --host --port 3000
  #     "
  #   restart: unless-stopped
  #   networks: [app-net]
  #   depends_on:
  #     backend:
  #       condition: service_started
  #     db:
  #       condition: service_healthy

volumes:
  pgdata:
    name: pgdata
  redis_data:
    name: redis_data

networks:
  app-net: {}
